schema = 1

[root]
name = "vapor-root"
organization = "ghf-studios"
version = "0.5.0"
repository = "https://github.com/GHF-Studios/Vapor-Root"

[root.steam]
app-id = 2122620
depot-id = 2122621
development-branch = "vapor-dev"

[root.runtime]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-gnullvm",
]

[[root.content]]
id = "ghf-studios/loo-cast/spacetime-engine"
kind = "engine"
app-id = 2122620
workshop-id = "3762162251"

[[root.content]]
id = "ghf-studios/loo-cast/loo-cast-game"
kind = "game"
app-id = 2122620
workshop-id = "3762162407"

[[root.content]]
id = "ghf-studios/loo-cast/loo-cast-packagepack"
kind = "packagepack"
app-id = 2122620
workshop-id = "3762162548"
default-launch = "loo-cast"
